---
- name: Install
  kewlfft.aur.aur:
    use: yay
    state: latest
    name:
      - lazygit

- name: Ensure config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/lazydocker"
    state: directory

- name: Copy config.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/lazydocker/config.yml"
    src: config.yml
