---
- name: Install
  ansible.builtin.package:
    name:
      - k9s
    state: latest
  become: yes

- name: Directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory

