---
- name: Make temp downlaod directory
  ansible.builtin.file:
    path: /tmp/k9s
    state: directory

- name: Download k9s
  ansible.builtin.unarchive:
    src: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_x86_64.tar.gz
    dest: /tmp/k9s
    remote_src: true

- name: Install k9s
  ansible.builtin.copy:
    src: /tmp/k9s/k9s
    dest: /usr/local/bin/k9s
  become: yes

- name: Set ownership/permissions on k9s
  ansible.builtin.file:
    path: "/usr/local/bin/k9s"
    mode: a+x
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: yes

- name: Delete download
  ansible.builtin.file:
    path: /tmp/k9s
    state: absent

