---
- hosts: localhost
  connection: local

  vars:
    is_wsl: "{% if ansible_env.WSL_DISTRO_NAME is defined %}true{% else %}false{%endif%}"

  roles:
    - role: system
    - role: git
    - role: zsh
    - role: oh-my-zsh
    - role: docker
      when: is_wsl|default(false)|bool == false
    - role: gantsign.golang
      golang_version: '1.19.3'
    - role: neovim
    - role: cimon-io.asdf
      become: true
      asdf_user: "{{ ansible_user_id }}"
      asdf_group: "{{ ansible_user_id }}"
      asdf_plugins:
        - name: "nodejs"
          versions: ["lts"]
          global: "lts"
        - name: "kubectl"
          versions: ["1.23.14", "1.24.8"]
          global: "1.23.14"
    - role: k9s

