---
- hosts: localhost
  connection: local

  roles:
    - role: system
    - role: git
    - role: zsh
    - role: oh-my-zsh
    - role: docker
      when: install_docker
      become: yes
    - role: gantsign.golang
      golang_version: '1.20.2'
    - role: neovim
    - role: cimon-io.asdf
      become: true
      asdf_user: "{{ ansible_user_id }}"
      asdf_group: "{{ ansible_user_id }}"
      asdf_plugins:
        - name: just
          versions: ["latest"]
          global: "latest"
        - name: k9s
          versions: ["latest"]
          global: "latest"
        - name: helm
          versions: ["latest"]
          global: "latest"
        - name: "nodejs"
          versions: ["18.16.0"]
          global: "18.16.0"
        - name: "kubectl"
          versions: ["latest"]
          global: "latest"
        - name: "minikube"
          versions: ["latest"]
          global: "latest"
    - role: diodonfrost.pulumi
      become: yes
    - role: 1pass
      become: yes
    - role: lazygit
    - role: sshconfig-1password
    - role: vivid
    - role: wsl
      when: is_wsl

