---
- name: Install
  ansible.builtin.package:
    name:
      - vivid
    state: latest
  become: yes

- name: Ensure .config/vivid directory
  file:
    path: "{{ ansible_user_dir }}/.config/vivid/themes"
    state: directory

- name: Download/Update vivid catppuccin-macchiato theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/sharkdp/vivid/master/themes/catppuccin-macchiato.yml
    dest: "{{ ansible_user_dir }}/.config/vivid/themes"
