---
- name: Install
  ansible.builtin.package:
    name:
      - jq
      - fzf
      - ripgrep
      - curl
      - ldns
      - nmap
      - net-tools
      - 7-zip-full
      - htop
      - socat
    state: latest
  become: yes

- name: Setup directory structure
  ansible.builtin.file:
    path: "{{ansible_user_dir}}/dev"
    state: directory

- name: Setup directory structure
  ansible.builtin.file:
    path: "{{ansible_user_dir}}/dev/repo"
    state: directory

