---
- name: Set sudo 
  ansible.builtin.copy:
    content: "{{ansible_env.USER}} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/10-brokkr
  become: yes

- name: Install
  ansible.builtin.package:
    name:
      - jq
      - fzf
      - ripgrep
      - curl
      - dnsutils
      - nmap
      - net-tools
      - p7zip-full
      - htop
      - socat
    state: latest
  become: yes

- name: Setup directory structure
  ansible.builtin.file:
    path: "{{ansible_user_dir}}/dev"
    state: directory

- name: Setup directory structure
  ansible.builtin.file:
    path: "{{ansible_user_dir}}/dev/repo"
    state: directory

