---
- name: Install
  ansible.builtin.package:
    name:
      - kitty
    state: latest
  become: yes

- name: Ensure config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy config.yml
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/.config/kitty/kitty.conf" 
    remote_src: yes
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf.default"

- name: Copy config.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    src: kitty.conf

