---
- name: Existing install
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: Download oh-my-zsh
  get_url:
    dest: /tmp/zsh-install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: not install.stat.exists

- name: Execute zsh-install.sh
  shell: /tmp/zsh-install.sh
  when: not install.stat.exists

- name: Remove zsh-install.sh
  file:
    path: /tmp/zsh-install.sh
    state: absent

- name: Copy .zshrc
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: .zshrc.j2

- name: Clone powerlevel10k
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    repo: https://github.com/romkatv/powerlevel10k.git
    single_branch: yes
    update: yes
    version: master
