---
- name: Install tmux
  ansible.builtin.package:
    name:
      - tmux
    state: latest
  become: yes

- name: Clone tpm
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    force: yes
    repo: https://github.com/tmux-plugins/tpm
    update: yes
    version: "master"

- name: copy tmux.conf
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: tmux.conf
