---
- name: Install
  ansible.builtin.package:
    name:
      - neovim
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Clone nvim config
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: yes
    repo: git@github.com:ThisDevDane/nvim-config.git
    update: yes
 
