---
- name: Dependencies
  package:
    name:
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen
    state: latest
  become: yes

- name: Existing tree-sitter install
  stat:
    path: "/usr/local/bin/tree-sitter"
  register: install_ts

- name: Download tree-sitter
  ansible.builtin.get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz
    dest: /tmp/tree-sitter-linux-x64.gz
  when: not install_ts.stat.exists
 
- name: Unarchive tree-sitter
  ansible.builtin.unarchive:
    src: /tmp/tree-sitter-linux-x64.gz
    dest: /usr/local/bin
  when: not install_ts.stat.exists

- name: Clone
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.cache/neovim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    update: yes
    version: "{{ neovim_version | default('stable') }}"
  register: clone

- name: Build
  make:
    chdir: "{{ ansible_user_dir }}/.cache/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

- name: Install
  make:
    chdir: "{{ ansible_user_dir }}/.cache/neovim"
    target: install
  become: yes
  when: clone.changed

- name: Remove build folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.cache/neovim/build"
    state: absent
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Clone nvim config
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: yes
    repo: https://github.com/ThisDrunkDane/nvim-config
    update: yes
    version: "new"
 
